//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportifMan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entitéathléte
    {
        public Nullable<System.DateTime> Date_debut { get; set; }
        public Nullable<System.DateTime> Date_Fin { get; set; }
        public int AthléteID { get; set; }
        public int Entité_sportifID { get; set; }
    
        public virtual Entitésportif Entitésportif { get; set; }
        public virtual Athléte Athléte { get; set; }
    }
}
