//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportifMan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Performance
    {
        public Nullable<double> Valeur { get; set; }
        public int ida { get; set; }
        public int idc { get; set; }
        public int idca { get; set; }
        public int idco { get; set; }
    
        public virtual CatégorieAge CatégorieAge { get; set; }
        public virtual Compétition Compétition { get; set; }
        public virtual Critère Critère { get; set; }
        public virtual Athléte Athléte { get; set; }
    }
}
