//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportifMan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Santéathléte
    {
        public int ID { get; set; }
        public Nullable<int> Valeur { get; set; }
        public Nullable<int> Date_exam { get; set; }
        public Nullable<int> Critére_santéID { get; set; }
        public Nullable<int> AthléteID { get; set; }
    
        public virtual Critére_santé Critére_santé { get; set; }
        public virtual Athléte Athléte { get; set; }
    }
}
